# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee263bbc6bc95d767fd4c56b6a066a25380a5719632a7a19be592cdf7c215efdc15ca824de7f1e51d11c06f5f3adcf5c32209deb6234191ac5891e3e3a9a4800

test:
  secret_key_base: f9a70d3e4a74595878807cb7b077033ee23165160e8b469f7e4378ae71b6983649b9ec4665f5ee1ef3a7d95314e86cf80601f1917845c648e921fb9cb7d9ad85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
